<a href="https://colab.research.google.com/github/VIDIPKUMAR/credit_card_fraud_detection.ipynb/blob/main/credit_card_fraud_detetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
dataset = pd.read_csv('fraudTest.csv')


In [ ]:
dataset = dataset.dropna(subset=['is_fraud'])

In [ ]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
dataset.shape

(555719, 23)

In [ ]:
dataset.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

In [ ]:
dataset.tail()

Unnamed: 0 trans_date_trans_time            cc_num  \
555714      555714   2020-12-31 23:59:07    30560609640617   
555715      555715   2020-12-31 23:59:09  3556613125071656   
555716      555716   2020-12-31 23:59:15  6011724471098086   
555717      555717   2020-12-31 23:59:24     4079773899158   
555718      555718   2020-12-31 23:59:34  4170689372027579   

                     merchant        category     amt    first     last  \
555714  fraud_Reilly and Sons  health_fitness   43.77  Michael    Olson   
555715   fraud_Hoppe-Parisian       kids_pets  111.84     Jose  Vasquez   
555716        fraud_Rau-Robel       kids_pets   86.88      Ann   Lawson   
555717  fraud_Breitenberg LLC          travel    7.99     Eric  Preston   
555718      fraud_Dare-Marvin   entertainment   38.13   Samuel     Frey   

       gender                      street  ...      lat      long  city_pop  \
555714      M         558 Michael Estates  ...  40.4931  -91.8912       519   
555715      M         572 Davis Mountains  ...  29.0393  -95.4401     28739   
555716      F  144 Evans Islands Apt. 683  ...  46.1966 -118.9017      3684   
555717      M  7020 Doyle Stream Apt. 951  ...  44.6255 -116.4493       129   
555718      M    830 Myers Plaza Apt. 384  ...  35.6665  -97.4798    116001   

                   job         dob                         trans_num  \
555714    Town planner  1966-02-13  9b1f753c79894c9f4b71f04581835ada   
555715  Futures trader  1999-12-27  2090647dac2c89a1d86c514c427f5b91   
555716        Musician  1981-11-29  6c5b7c8add471975aa0fec023b2e8408   
555717    Cartographer  1965-12-15  14392d723bb7737606b2700ac791b7aa   
555718     Media buyer  1993-05-10  1765bb45b3aa3224b4cdcb6e7a96cee3   

         unix_time  merch_lat  merch_long  is_fraud  
555714  1388534347  39.946837  -91.333331         0  
555715  1388534349  29.661049  -96.186633         0  
555716  1388534355  46.658340 -119.715054         0  
555717  1388534364  44.470525 -117.080888         0  
555718  1388534374  36.210097  -97.036372         0  

[5 rows x 23 columns]

In [ ]:
dataset.describe()


Unnamed: 0        cc_num            amt            zip  \
count  555719.000000  5.557190e+05  555719.000000  555719.000000   
mean   277859.000000  4.178387e+17      69.392810   48842.628015   
std    160422.401459  1.309837e+18     156.745941   26855.283328   
min         0.000000  6.041621e+10       1.000000    1257.000000   
25%    138929.500000  1.800429e+14       9.630000   26292.000000   
50%    277859.000000  3.521417e+15      47.290000   48174.000000   
75%    416788.500000  4.635331e+15      83.010000   72011.000000   
max    555718.000000  4.992346e+18   22768.110000   99921.000000   

                 lat           long      city_pop     unix_time  \
count  555719.000000  555719.000000  5.557190e+05  5.557190e+05   
mean       38.543253     -90.231325  8.822189e+04  1.380679e+09   
std         5.061336      13.721780  3.003909e+05  5.201104e+06   
min        20.027100    -165.672300  2.300000e+01  1.371817e+09   
25%        34.668900     -96.798000  7.410000e+02  1.376029e+09   
50%        39.371600     -87.476900  2.408000e+03  1.380762e+09   
75%        41.894800     -80.175200  1.968500e+04  1.385867e+09   
max        65.689900     -67.950300  2.906700e+06  1.388534e+09   

           merch_lat     merch_long       is_fraud  
count  555719.000000  555719.000000  555719.000000  
mean       38.542798     -90.231380       0.003860  
std         5.095829      13.733071       0.062008  
min        19.027422    -166.671575       0.000000  
25%        34.755302     -96.905129       0.000000  
50%        39.376593     -87.445204       0.000000  
75%        41.954163     -80.264637       0.000000  
max        66.679297     -66.952026       1.000000

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Unnamed: 0             555719 non-null  int64  
 1   trans_date_trans_time  555719 non-null  object 
 2   cc_num                 555719 non-null  int64  
 3   merchant               555719 non-null  object 
 4   category               555719 non-null  object 
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  object 
 7   last                   555719 non-null  object 
 8   gender                 555719 non-null  object 
 9   street                 555719 non-null  object 
 10  city                   555719 non-null  object 
 11  state                  555719 non-null  object 
 12  zip                    555719 non-null  int64  
 13  lat                    555719 non-null  float64
 14  long                   555719 non-nu

In [ ]:
label_columns = ['gender', 'merchant', 'city', 'state', 'job']
le = LabelEncoder()
for col in label_columns:
    dataset[col] = le.fit_transform(dataset[col])

In [ ]:
X = dataset.drop(columns=['is_fraud'])
y = dataset['is_fraud']

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train.dtypes)

Unnamed: 0                 int64
trans_date_trans_time     object
cc_num                     int64
merchant                   int64
category                  object
amt                      float64
first                     object
last                      object
gender                     int64
street                    object
city                       int64
state                      int64
zip                        int64
lat                      float64
long                     float64
city_pop                   int64
job                        int64
dob                       object
trans_num                 object
unix_time                  int64
merch_lat                float64
merch_long               float64
dtype: object


In [ ]:
X_train = X_train.drop(columns=['trans_date_trans_time'])
X_test = X_test.drop(columns=['trans_date_trans_time'])

In [ ]:
X_train = pd.get_dummies(X_train, columns=['category'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['category'], drop_first=True)

In [ ]:
X_train, X_test = X_train.align(X_test, axis=1, fill_value=0)


In [ ]:
le = LabelEncoder()
X_train['gender'] = le.fit_transform(X_train['gender'])
X_test['gender'] = le.transform(X_test['gender'])


In [ ]:
print(X_train.isnull().sum())
print(X_train.select_dtypes(include=['object']).head())

Unnamed: 0                 0
cc_num                     0
merchant                   0
amt                        0
first                      0
last                       0
gender                     0
street                     0
city                       0
state                      0
zip                        0
lat                        0
long                       0
city_pop                   0
job                        0
dob                        0
trans_num                  0
unix_time                  0
merch_lat                  0
merch_long                 0
category_food_dining       0
category_gas_transport     0
category_grocery_net       0
category_grocery_pos       0
category_health_fitness    0
category_home              0
category_kids_pets         0
category_misc_net          0
category_misc_pos          0
category_personal_care     0
category_shopping_net      0
category_shopping_pos      0
category_travel            0
dtype: int64
          first     last      

In [ ]:
X_train = X_train.fillna(0)
X_test = X_test.fillna(0)


In [ ]:
numerical_columns = X_train.select_dtypes(include=['number']).columns
X_train = X_train[numerical_columns]
X_test = X_test[numerical_columns]


In [ ]:
print(X_train)

        Unnamed: 0            cc_num  merchant     amt  gender  city  state  \
427945      427945  4129767952109660       257   77.05       0   302     22   
153356      153356  3561963695236764       482   56.60       1   705     33   
468630      468630  3576431665303017        82  119.81       0   606      3   
232805      232805  4430881574719618       392    7.51       0   474      5   
325614      325614  2720433095629877       519   70.61       1    82     20   
...            ...               ...       ...     ...     ...   ...    ...   
359783      359783  6011366578560244       153   72.01       1   470     37   
152315      152315  4935858973307492        85   48.22       1   360      9   
117952      117952  4124536010991657       154    9.83       0   242      1   
435829      435829  4104312520615374         7   27.17       0   515      4   
305711      305711    30510856607165       254    4.89       1   425     21   

          zip      lat      long  city_pop  job   u

In [ ]:
print(y_train)

427945    0
153356    0
468630    0
232805    0
325614    0
         ..
359783    0
152315    0
117952    0
435829    0
305711    0
Name: is_fraud, Length: 444575, dtype: int64


In [ ]:
print(X_test)

        Unnamed: 0               cc_num  merchant     amt  gender  city  \
102051      102051     4789911625179723       239  218.76       0   501   
270705      270705      213193596103206       542   48.83       1   612   
308877      308877         502038091380       490   70.86       1   394   
465523      465523     3598895972308782        70    4.74       1   555   
358267      358267       30238755902988       454    9.75       0   760   
...            ...                  ...       ...     ...     ...   ...   
181829      181829      345933964507467        43   65.07       0   827   
382824      382824     4294040533480516        91   48.60       0   527   
39243        39243  4210078554961359092       285   76.65       0   439   
177861      177861       30033162392091       282   97.43       1   118   
92850        92850      374930071163758       398   37.38       1   663   

        state    zip      lat      long  city_pop  job   unix_time  merch_lat  \
102051     33  119

In [ ]:
print(y_test)

102051    0
270705    0
308877    0
465523    0
358267    0
         ..
181829    0
382824    0
39243     0
177861    0
92850     0
Name: is_fraud, Length: 111144, dtype: int64


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 0.93 -0.32 -0.43 ...  1.04  1.75 -0.48]
 [-0.78 -0.32  0.69 ... -0.82  0.33  1.34]
 [ 1.19 -0.32 -1.3  ...  1.2  -1.03 -1.65]
 ...
 [-1.   -0.32 -0.94 ... -1.02 -1.54  0.12]
 [ 0.98 -0.32 -1.67 ...  1.08 -1.07 -1.94]
 [ 0.17 -0.32 -0.44 ...  0.21  0.94  0.48]]


In [ ]:
print(X_test)

[[-1.1  -0.32 -0.52 ... -1.11  0.32  1.22]
 [-0.04 -0.32  0.99 ... -0.04  1.6   0.38]
 [ 0.19 -0.32  0.73 ...  0.24 -0.41 -0.14]
 ...
 [-1.49  2.9  -0.29 ... -1.48  1.19 -2.39]
 [-0.62 -0.32 -0.3  ... -0.66  0.91 -0.49]
 [-1.15 -0.32  0.27 ... -1.17  0.6   0.57]]


## Training the Decision Tree Regression model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
y_test_array = np.array(y_test)

In [ ]:
import numpy as np
y_pred_reshaped = y_pred.reshape(len(y_pred), 1)
y_test_reshaped = y_test_array.reshape(len(y_test_array), 1)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_reshaped, y_test_reshaped), axis=1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Predicting the Test set results

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred_reshaped, y_test_reshaped), axis=1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


## Evaluating the Model Performance

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[110471    232]
 [   220    221]]


0.9959332037716836